<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="9" passed="8">
  <reporter-output>
  </reporter-output>
  <suite name="Parallel Suite" duration-ms="121" started-at="2019-04-24T10:52:53Z" finished-at="2019-04-24T10:52:53Z">
    <groups>
    </groups>
    <test name="Test I" duration-ms="49" started-at="2019-04-24T10:52:53Z" finished-at="2019-04-24T10:52:53Z">
      <class name="Test_ParallelOne">
        <test-method status="PASS" signature="veritySumForDouble(double, double)[pri:0, instance:Test_ParallelOne@4411d970]" name="veritySumForDouble" duration-ms="9" started-at="2019-04-24T10:52:53Z" finished-at="2019-04-24T10:52:53Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[6.4]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[3.8]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- veritySumForDouble -->
        <test-method status="PASS" signature="veritySumForNegative(int, int)[pri:0, instance:Test_ParallelOne@4411d970]" name="veritySumForNegative" duration-ms="9" started-at="2019-04-24T10:52:53Z" finished-at="2019-04-24T10:52:53Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[-5]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[-10]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- veritySumForNegative -->
      </class> <!-- Test_ParallelOne -->
    </test> <!-- Test I -->
    <test name="Test II" duration-ms="2" started-at="2019-04-24T10:52:53Z" finished-at="2019-04-24T10:52:53Z">
      <class name="Test_ParallelTwo">
        <test-method status="PASS" signature="veritySumForNegative(int, int)[pri:0, instance:Test_ParallelTwo@17550481]" name="veritySumForNegative" duration-ms="0" started-at="2019-04-24T10:52:53Z" finished-at="2019-04-24T10:52:53Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[-5]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[-10]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- veritySumForNegative -->
        <test-method status="PASS" signature="veritySumForDouble(double, double)[pri:0, instance:Test_ParallelTwo@17550481]" name="veritySumForDouble" duration-ms="0" started-at="2019-04-24T10:52:53Z" finished-at="2019-04-24T10:52:53Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[6.4]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[3.8]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- veritySumForDouble -->
      </class> <!-- Test_ParallelTwo -->
    </test> <!-- Test II -->
  </suite> <!-- Parallel Suite -->
  <suite name="Regression Suite" duration-ms="26" started-at="2019-04-24T10:52:53Z" finished-at="2019-04-24T10:52:53Z">
    <groups>
      <group name="print">
        <method signature="Test_Annotations.verifyTestMethod()[pri:1, instance:Test_Annotations@6fb554cc]" name="verifyTestMethod" class="Test_Annotations"/>
        <method signature="Test_Annotations.veritySumForDouble()[pri:2, instance:Test_Annotations@6fb554cc]" name="veritySumForDouble" class="Test_Annotations"/>
        <method signature="Test_Annotations.veritySumForNegative()[pri:3, instance:Test_Annotations@6fb554cc]" name="veritySumForNegative" class="Test_Annotations"/>
        <method signature="Test_Dashboard.verifySumOfTwoNumbers()[pri:0, instance:Test_Dashboard@47f6473]" name="verifySumOfTwoNumbers" class="Test_Dashboard"/>
      </group> <!-- print -->
      <group name="sum">
        <method signature="Test_Annotations.veritySumForDouble()[pri:2, instance:Test_Annotations@6fb554cc]" name="veritySumForDouble" class="Test_Annotations"/>
        <method signature="Test_Annotations.veritySumForNegative()[pri:3, instance:Test_Annotations@6fb554cc]" name="veritySumForNegative" class="Test_Annotations"/>
        <method signature="Test_Dashboard.verifySumOfTwoNumber()[pri:0, instance:Test_Dashboard@47f6473]" name="verifySumOfTwoNumber" class="Test_Dashboard"/>
        <method signature="Test_Dashboard.verifySumOfTwoNumbers()[pri:0, instance:Test_Dashboard@47f6473]" name="verifySumOfTwoNumbers" class="Test_Dashboard"/>
      </group> <!-- sum -->
    </groups>
    <test name="Calculator" duration-ms="4" started-at="2019-04-24T10:52:53Z" finished-at="2019-04-24T10:52:53Z">
      <class name="Test_Annotations">
        <test-method status="PASS" signature="verifyTestMethod()[pri:1, instance:Test_Annotations@6fb554cc]" name="verifyTestMethod" duration-ms="0" started-at="2019-04-24T10:52:53Z" finished-at="2019-04-24T10:52:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyTestMethod -->
        <test-method status="PASS" signature="veritySumForDouble()[pri:2, instance:Test_Annotations@6fb554cc]" name="veritySumForDouble" duration-ms="1" started-at="2019-04-24T10:52:53Z" finished-at="2019-04-24T10:52:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- veritySumForDouble -->
        <test-method status="PASS" signature="veritySumForNegative()[pri:3, instance:Test_Annotations@6fb554cc]" name="veritySumForNegative" duration-ms="0" started-at="2019-04-24T10:52:53Z" finished-at="2019-04-24T10:52:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- veritySumForNegative -->
      </class> <!-- Test_Annotations -->
    </test> <!-- Calculator -->
    <test name="Dashboard" duration-ms="9" started-at="2019-04-24T10:52:53Z" finished-at="2019-04-24T10:52:53Z">
      <class name="Test_Dashboard">
        <test-method status="FAIL" signature="verifySumOfTwoNumber()[pri:0, instance:Test_Dashboard@47f6473]" name="verifySumOfTwoNumber" duration-ms="1" started-at="2019-04-24T10:52:53Z" finished-at="2019-04-24T10:52:53Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [9] but found [10]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [9] but found [10]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at Test_Dashboard.verifySumOfTwoNumber(Test_Dashboard.java:21)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifySumOfTwoNumber -->
        <test-method status="PASS" signature="verifySumOfTwoNumbers()[pri:0, instance:Test_Dashboard@47f6473]" name="verifySumOfTwoNumbers" duration-ms="1" started-at="2019-04-24T10:52:53Z" finished-at="2019-04-24T10:52:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifySumOfTwoNumbers -->
      </class> <!-- Test_Dashboard -->
    </test> <!-- Dashboard -->
  </suite> <!-- Regression Suite -->
</testng-results>
